export const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  UNAUTHORIZED: "/unauthorized",
  DASHBOARD: "/dashboard",
  TRANSACTIONS: "/transactions",
  TRANSACTIONS_ADD: "/transactions/add",
  ACCOUNTS: "/accounts",
  JARS: "/jars",
  /** Giới hạn chi tiêu — khớp BE `GET/POST /api/v1/limits`. */
  LIMITS: "/limits",
  CATEGORIES: "/categories",
  REMINDERS: "/reminders",
  IMPORTS_OCR: "/imports/ocr",
  AI_CHAT: "/ai-chat",
  GOALS: "/goals",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  ONBOARDING: "/onboarding",
  ADMIN_DASHBOARD: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_NOTIFICATIONS: "/admin/notifications",
  ADMIN_AUDIT_LOGS: "/admin/audit-logs",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_AI_SETTINGS: "/admin/ai-settings",
} as const;
